name: Push test to S3

on:
  push:
    branches:
      - dev
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
      - name: Branch name
        run: echo running on branch ${{ github.head_ref || github.ref_name }} 
      - name: Path
        run: aws s3 ls
      - name: Push to S3
        run: aws s3 cp e2e s3://doomo-e2e-files/dev  --recursive
